shopping_navigation_prompt = """
When you search for a product, you should first search the product in the following hierarchy to navigate the website.
**Shopping Navigation Hierarchy:**
  - **Oral Care:** `Beauty & Personal Care -> Oral Care -> (Toothbrushes & Accessories, Dental Floss & Picks, Orthodontic Supplies, Children's Dental Care, Oral Pain Relief, Toothpaste, Teeth Whitening, Breath Fresheners, Denture Care, Tongue Cleaners, Mouthwash)`
  - **Skin Care:** `Beauty & Personal Care -> Skin Care -> (Sunscreens & Tanning Products, Face, Lip Care, Maternity, Eyes, Sets & Kits, Body)`
  - **Makeup:** `Beauty & Personal Care -> Makeup -> (Body, Eyes, Lips, Makeup Palettes, Face, Makeup Sets, Makeup Remover)`
  - **Foot, Hand & Nail Care:** `Beauty & Personal Care -> Foot, Hand & Nail Care -> (Tools & Accessories, Nail Art & Polish, Foot & Hand Care)`
  - **Hair Care:** `Beauty & Personal Care -> Hair Care -> (Hair Loss Products, Hair Masks, Hair Cutting Tools, Hair Coloring Products, Hair Treatment Oils, Hair Extensions, Wigs & Accessories, Shampoo & Conditioner, Styling Products, Styling Tools & Appliances, Hair Accessories)`
  - **Tools & Accessories:** `Beauty & Personal Care -> Tools & Accessories -> (Bags & Cases, Makeup Brushes & Tools, Refillable Containers, Mirrors, Skin Care Tools, Cotton Balls & Swabs)`
  - **Fragrance:** `Beauty & Personal Care -> Fragrance -> (Women's, Men's)`
  - **Personal Care:** `Beauty & Personal Care -> Personal Care -> (Bath & Bathing Accessories, Deodorants & Antiperspirants, Piercing & Tattoo Supplies)`
  - **Shave & Hair Removal:** `Beauty & Personal Care -> Shave & Hair Removal -> (Men's, Women's)`
  - **Salon & Spa Equipment:** `Beauty & Personal Care -> Salon & Spa Equipment -> (Spa Storage Systems, Spa Beds & Tables, Professional Massage Equipment)`
  - **Hunting & Fishing:** `Sports & Outdoors -> Hunting & Fishing -> (Shooting)`
  - **Exercise & Fitness:** `Sports & Outdoors -> Exercise & Fitness`
  - **Fan Shop:** `Sports & Outdoors -> Fan Shop -> (Clothing, Footwear)`
  - **Sports & Outdoor Recreation Accessories:** `Sports & Outdoors -> Sports & Outdoor Recreation Accessories -> (Ball Storage)`
  - **Sports:** `Sports & Outdoors -> Sports`
  - **Men:** `Clothing, Shoes & Jewelry -> Men -> (Clothing, Shoes, Uniforms, Work & Safety)`
  - **Women:** `Clothing, Shoes & Jewelry -> Women -> (Clothing, Shoes, Accessories, Uniforms, Work & Safety)`
  - **Novelty & More:** `Clothing, Shoes & Jewelry -> Novelty & More -> (Clothing)`
  - **Sport Specific Clothing:** `Clothing, Shoes & Jewelry -> Sport Specific Clothing -> (Competitive Swimwear)`
  - **Furniture:** `Home & Kitchen -> Furniture -> (Living Room Furniture, Accent Furniture, Home Office Furniture, Kitchen Furniture, Game & Recreation Room Furniture, Bedroom Furniture, Entryway Furniture, Dining Room Furniture, Kids' Furniture)`
  - **Bedding:** `Home & Kitchen -> Bedding -> (Kids' Bedding, Blankets & Throws, Decorative Pillows, Inserts & Covers)`
  - **Storage & Organization:** `Home & Kitchen -> Storage & Organization -> (Baskets, Bins & Containers, Home Storage Hooks, Racks, Shelves & Drawers, Clothing & Closet Storage)`
  - **Home Décor Products:** `Home & Kitchen -> Home Décor Products -> (Home Décor Accents, Window Treatments, Artificial Plants & Flowers, Candles & Holders, Mirrors, Rugs, Pads & Protectors, Slipcovers)`
  - **Kitchen & Dining:** `Home & Kitchen -> Kitchen & Dining -> (Dining & Entertaining, Storage & Organization, Kitchen & Table Linens)`
  - **Heating, Cooling & Air Quality:** `Home & Kitchen -> Heating, Cooling & Air Quality`
  - **Wall Art:** `Home & Kitchen -> Wall Art -> (Posters & Prints)`
  - **Bath:** `Home & Kitchen -> Bath -> (Bathroom Accessories)`
  - **Office Electronics:** `Office Products -> Office Electronics -> (Printers & Accessories)`
  - **Office & School Supplies:** `Office Products -> Office & School Supplies -> (Desk Accessories & Workspace Organizers)`
  - **Office Furniture & Lighting:** `Office Products -> Office Furniture & Lighting -> (Chairs & Sofas, Cabinets, Racks & Shelves)`
  - **Lighting & Ceiling Fans:** `Tools & Home Improvement -> Lighting & Ceiling Fans -> (Lamps & Shades, Wall Lights, Ceiling Lights)`
  - **Household Supplies:** `Health & Household -> Household Supplies -> (Household Batteries)`
  - **Health Care:** `Health & Household -> Health Care`
  - **Diet & Sports Nutrition:** `Health & Household -> Diet & Sports Nutrition -> (Nutrition Bars & Drinks)`
  - **Gardening & Lawn Care:** `Patio, Lawn & Garden -> Gardening & Lawn Care -> (Plants, Seeds & Bulbs, Pots, Planters & Container Accessories)`
  - **Patio Furniture & Accessories:** `Patio, Lawn & Garden -> Patio Furniture & Accessories`
  - **Home Audio:** `Electronics -> Home Audio -> (Home Audio Accessories, Speakers, Compact Radios & Stereos, Home Theater, Turntables & Accessories)`
  - **Video Projectors:** `Electronics -> Video Projectors`
  - **Accessories & Supplies:** `Electronics -> Accessories & Supplies -> (Audio & Video Accessories, Power Strips & Surge Protectors, Telephone Accessories)`
  - **Television & Video:** `Electronics -> Television & Video -> (Projection Screens, Televisions, DVD Players & Recorders, Streaming Media Players, Home Theater Systems, Television Accessories)`
  - **Camera & Photo:** `Electronics -> Camera & Photo -> (Tripods & Monopods, Lighting & Studio, Bags & Cases, Binoculars & Scopes, Video Surveillance, Accessories, Digital Cameras, Underwater Photography, Film Photography, Flashes, Lenses, Video)`
  - **Computers & Accessories:** `Electronics -> Computers & Accessories -> (Computer Accessories & Peripherals, Networking Products, Tablet Accessories, Computers & Tablets, Data Storage, Laptop Accessories, Computer Components)`
  - **Headphones:** `Electronics -> Headphones -> (Over-Ear Headphones, Earbud Headphones, On-Ear Headphones)`
  - **Portable Audio & Video:** `Electronics -> Portable Audio & Video -> (Boomboxes, Portable Speakers & Docks, Radios, MP3 & MP4 Player Accessories)`
  - **Security & Surveillance:** `Electronics -> Security & Surveillance -> (Accessories, Surveillance Video Equipment)`
  - **Power Accessories:** `Electronics -> Power Accessories -> (AC Adapters)`
  - **Car & Vehicle Electronics:** `Electronics -> Car & Vehicle Electronics -> (Car Electronics, Vehicle Electronics Accessories)`
  - **Wearable Technology:** `Electronics -> Wearable Technology -> (Smartwatches)`
  - **GPS, Finders & Accessories:** `Electronics -> GPS, Finders & Accessories -> (GPS System Accessories)`
  - **Accessories:** `Cell Phones & Accessories -> Accessories -> (Chargers & Power Adapters, Maintenance, Upkeep & Repairs, Single Ear Bluetooth Headsets, Smartwatch Accessories, Virtual Reality (VR) Headsets, Stands, Automobile Accessories, Photo & Video Accessories, Signal Boosters)`
  - **Cases, Holsters & Sleeves:** `Cell Phones & Accessories -> Cases, Holsters & Sleeves -> (Basic Cases, Flip Cases)`
  - **Cell Phones:** `Cell Phones & Accessories -> Cell Phones`
  - **Xbox One:** `Video Games -> Xbox One -> (Accessories)`
  - **PC:** `Video Games -> PC -> (Accessories, Virtual Reality)`
  - **Legacy Systems:** `Video Games -> Legacy Systems -> (Xbox Systems, PlayStation Systems, Nintendo Systems)`
  - **PlayStation 4:** `Video Games -> PlayStation 4 -> (Accessories)`
  - **Nintendo Switch:** `Video Games -> Nintendo Switch`
  - **Food & Beverage Gifts:** `Grocery & Gourmet Food -> Food & Beverage Gifts -> (Bakery & Dessert Gifts, Snack Gifts, Coffee & Tea Gifts, Fruit & Nut Gifts, Herb, Spice & Seasoning Gifts, Assortments & Variety Gifts, Meat & Seafood Gifts, Cheese & Charcuterie Gifts)`
  - **Breads & Bakery:** `Grocery & Gourmet Food -> Breads & Bakery -> (Cookies, Breads, Cakes, Pastries & Bakery)`
  - **Pantry Staples:** `Grocery & Gourmet Food -> Pantry Staples -> (Herbs, Spices & Seasonings, Cooking & Baking, Olives, Pickles & Relishes, Canned, Jarred & Packaged Foods, Sauces, Gravies & Marinades, Pasta & Noodles, Soups, Stocks & Broths, Dried Grains & Rice, Jams, Jellies & Sweet Spreads, Condiments & Salad Dressings, Nut & Seed Butters)`
  - **Snacks & Sweets:** `Grocery & Gourmet Food -> Snacks & Sweets -> (Snack Foods, Chocolate, Candy & Chocolate)`
  - **Dairy, Cheese & Eggs:** `Grocery & Gourmet Food -> Dairy, Cheese & Eggs -> (Cheese, Yogurt, Cheese Assortments & Samplers, Non-Dairy Milks, Milk & Cream)`
  - **Breakfast Foods:** `Grocery & Gourmet Food -> Breakfast Foods -> (Cereals, Breakfast & Cereal Bars)`
  - **Beverages:** `Grocery & Gourmet Food -> Beverages -> (Bottled Beverages, Water & Drink Mixes, Coffee, Tea & Cocoa)`
  - **Produce:** `Grocery & Gourmet Food -> Produce -> (Dried Fruits & Vegetables)`
  - **Alcoholic Beverages:** `Grocery & Gourmet Food -> Alcoholic Beverages -> (Wine)`
  - **Deli & Prepared Foods:** `Grocery & Gourmet Food -> Deli & Prepared Foods -> (Deli Meats & Cheeses)`
  - **Frozen:** `Grocery & Gourmet Food -> Frozen -> (Meals & Entrees, Meats, Ice Cream & Novelties, Appetizers & Snacks, Seafood)`
  - **Home Brewing & Winemaking:** `Grocery & Gourmet Food -> Home Brewing & Winemaking -> (Winemaking Ingredients)`
  - **Meat & Seafood:** `Grocery & Gourmet Food -> Meat & Seafood -> (Beef, Seafood)`
  - **Fresh Meal Kits:** `Grocery & Gourmet Food -> Fresh Meal Kits`
  - **Meat Substitutes:** `Grocery & Gourmet Food -> Meat Substitutes`
"""
