"""
Generic tool environment implementation, usable with any set of tools
"""
import os
import re
import json
import json_repair
import traceback
from typing import Dict, List, Any
from copy import deepcopy
from pathlib import Path
import concurrent.futures
import time
import uuid
import logging
import imagesize
import threading
import socketserver
from http.server import SimpleHTTPRequestHandler
from recipe.webagent_fully_async_policy.browser_env.action_space_json import ACTION_ID_LIST, ACTION_CORR_LIST
from recipe.webagent_fully_async_policy.browser_env.async_web_browser_envs import AsyncScriptBrowserEnv, BrowserActor
from typing import Optional
from PIL import Image
import re
from recipe.webagent_fully_async_policy.browser_env.web_browser_tool import WebBrowserTool
from recipe.webagent_fully_async_policy.browser_env.async_web_browser_envs import initialize_browser_actor_pool
# --- Dynamic Imports ---
from recipe.webagent_fully_async_policy.browser_env.async_web_browser_envs import AsyncScriptBrowserEnv

from recipe.webagent_fully_async_policy.browser_env.actions import create_id_based_action, create_coords_based_action
# --- Logger Setup ---
# 配置基础日志记录器，使其在所有模块中可用
logger = logging.getLogger(__name__)
logger.setLevel(os.getenv("VERL_LOGGING_LEVEL", "INFO"))
# --- Environment Variables ---
DIST_WEBBROWSER = os.environ.get('DIST_WEBBROWSER', 0)
OBSERVATION_TYPE = os.environ.get('OBSERVATION_TYPE', '')
MAX_CONCURRENT_WORKERS = int(os.environ.get('MAX_CONCURRENT_WORKERS', 32))
EXPERIMENT_NAME = os.environ.get('EXPERIMENT_NAME', "")
TASK_ID = os.environ.get("TASK_ID", "")
TENSORBOARD_DIR = os.environ.get("TENSORBOARD_DIR", "")
BROWSER_OUTPUT_PATH = TENSORBOARD_DIR.replace("tensorboard", "browser_config")
BROWSER_OUTPUT_PATH = BROWSER_OUTPUT_PATH + "/" + TASK_ID + "/"

import glob
# [MODIFIED] - 全局 ws_endpoint_list 在模块加载时准备好
ws_endpoint_list = []
try:
    browser_config_dir = BROWSER_OUTPUT_PATH
    browser_config_files = glob.glob(os.path.join(browser_config_dir, "*.json"))
    for file_path in browser_config_files:
        with open(file_path, 'r') as f:
            data = json.load(f)
        ws_endpoint_list.extend(data)
    logger.info(f"Loaded {len(ws_endpoint_list)} browser WebSocket endpoints.")
except Exception as e:
    logger.error(f"Failed to load browser WebSocket endpoints: {e}", exc_info=True)

# Independent step function
def step(env: 'ToolEnv', action_text: str, webloop: Any):
    """
    Execute one step of environment interaction

    Args:
        env: The tool environment
        action_text: Text generated by LLM

    Returns:
        (observation, reward, done, info)
    """
    env.steps_taken += 1
    action = env.extract_tool_call(action_text)

    if action == env.INVALID_ACTION:

        if env.extract_answer(action_text):
            reward = 0
            result = {"content": "", "image": None} 
        else:
            reward = env.PENALTY_FOR_INVALID  # Syntax error penalty
            result = {"content": "Invalid tool call format. Please use <tool_call>{\"name\": \"tool_name\", \"arguments\": {params_json}}</tool_call> format.", "image": None} # answer error penalty
        env._update_tracking_variables(
            response=action_text,
            action=action,
            action_is_valid=False,
            action_is_effective=False,
            reward=reward
        )
        return result, reward, False, {"action_is_valid": False, "action_is_effective": False}

    tool_name = action["tool"]
    tool_args = action["args"]
    # Validate if the tool exists
    if tool_name not in env.tool_map:
        result = {"content": f"Unknown tool: {tool_name}", "image": None}
        reward = env.PENALTY_FOR_INEFFECTIVE  # Semantic error penalty
        env._update_tracking_variables(
            response=action_text,
            action=action,
            action_is_valid=True,
            action_is_effective=False,
            reward=reward
        )
        return result, reward, False, {"action_is_valid": True, "action_is_effective": False}

    # Get tool instance
    tool = env.tool_map[tool_name]

    # Validate tool arguments
    try:
        is_valid, error_msg = tool.validate_args(tool_args)
    except Exception as e:
        logger.error(f"Error validating tool arguments for tool '{tool_name}': {e}")
        is_valid = False
        error_msg = str(e)

    if not is_valid:
        result = {"content": f"Invalid arguments for tool '{tool_name}': {error_msg}", "image": None}
        reward = env.PENALTY_FOR_INEFFECTIVE  # Semantic error penalty
        env._update_tracking_variables(
            response=action_text,
            action=action,
            action_is_valid=True,
            action_is_effective=False,
            reward=reward
        )
        return result, reward, False, {"action_is_valid": True, "action_is_effective": False}

    # Execute tool
    try:
        result = tool.execute(tool_args)
        reward = tool.calculate_reward(tool_args, result, env, env.PENALTY_FOR_INEFFECTIVE)

        # Record tool call history
        env.tool_history.append({
            "tool": tool_name,
            "args": tool_args,
            "result": result
        })

        # Check if max turns reached
        done = env.steps_taken >= env.max_turns

        env._update_tracking_variables(
            response=action_text,
            action=action,
            action_is_valid=True,
            action_is_effective=True,
            reward=reward
        )

        # Return the full result dictionary as observation
        if not isinstance(result, dict):
            result = {"content": str(result), "image": None}
        return result, reward, done, {"action_is_valid": True, "action_is_effective": True}
    except Exception as e:
        error_trace = traceback.format_exc()
        logger.error(f"Error executing tool '{tool_name}': {e}\nTraceback:\n{error_trace}")
        result = {"content": f"Error executing tool '{tool_name}': {str(e)}", "image": None}
        reward = env.PENALTY_FOR_INEFFECTIVE  # Runtime error penalty

        env._update_tracking_variables(
            response=action_text,
            action=action,
            action_is_valid=True,
            action_is_effective=False,
            reward=reward
        )

        return result, reward, False, {"action_is_valid": True, "action_is_effective": False}

# Batch step function
def step_batch(envs: List['ToolEnv'], action_texts: List[str]):
    """
    Execute batch steps of environment interaction

    Args:
        envs: List of tool environments
        action_texts: List of texts generated by LLM

    Returns:
        List of (observation, reward, done, info) tuples
    """
    assert len(envs) == len(action_texts), "Number of environments and actions must match"

    # Group actions by tool name and environment
    tool_groups = {}
    tool_indices = {}
    env_indices = {}
    raw_prediction_indices = {}
    action_map = {}
    results = [None] * len(envs)

    # First pass: extract tool calls and group by tool name
    for i, (env, action_text) in enumerate(zip(envs, action_texts)):
        # Extract the tool call
        action = env.extract_tool_call(action_text)
        action_map[i] = (env, action, action_text)

        # Handle invalid actions
        if action == env.INVALID_ACTION:
            result = {"content": "Invalid tool call format. Please use <tool_call>{\"name\": \"tool_name\", \"arguments\": {params_json}}</tool_call> format.", "image": None}
            env.steps_taken += 1
            env._update_tracking_variables(
                response=action_text,
                action=action,
                action_is_valid=False,
                action_is_effective=False,
                reward=env.PENALTY_FOR_INVALID  # Syntax error penalty
            )
            results[i] = (result, env.PENALTY_FOR_INVALID, False, {"action_is_valid": False, "action_is_effective": False})
            continue

        tool_name = action["tool"]
        tool_args = action["args"]

        if not isinstance(tool_name, str):
            result = {"content": f"Invalid tool name: {tool_name}", "image": None}
            env.steps_taken += 1
            env._update_tracking_variables(
                response=action_text,
                action=action,
                action_is_valid=True,
                action_is_effective=False,
                reward=env.PENALTY_FOR_INEFFECTIVE  # Semantic error penalty
            )
            results[i] = (result, env.PENALTY_FOR_INEFFECTIVE, False, {"action_is_valid": True, "action_is_effective": False})
            logger.warning(f"Invalid tool name: '{tool_name}' in action: {action_text} end-------")
            continue

        # Handle unknown tools
        if tool_name not in env.tool_map:
            result = {"content": f"Unknown tool: {tool_name}", "image": None}
            env.steps_taken += 1
            env._update_tracking_variables(
                response=action_text,
                action=action,
                action_is_valid=True,
                action_is_effective=False,
                reward=env.PENALTY_FOR_INEFFECTIVE  # Semantic error penalty
            )
            results[i] = (result, env.PENALTY_FOR_INEFFECTIVE, False, {"action_is_valid": True, "action_is_effective": False})
            logger.warning(f"Unknown tool: '{tool_name}' in action: {action_text} end-------")
            continue

        # Get tool instance
        tool = env.tool_map[tool_name]

        # Validate tool arguments
        try:
            is_valid, error_msg = tool.validate_args(tool_args)
        except Exception as e:
            logger.error(f"Error validating tool arguments for tool '{tool_name}': {e}")
            is_valid = False
            error_msg = str(e)

        if not is_valid:
            result = {"content": f"Invalid arguments for tool '{tool_name}': {error_msg}", "image": None}
            env.steps_taken += 1
            env._update_tracking_variables(
                response=action_text,
                action=action,
                action_is_valid=True,
                action_is_effective=False,
                reward=env.PENALTY_FOR_INEFFECTIVE  # Semantic error penalty
            )
            results[i] = (result, env.PENALTY_FOR_INEFFECTIVE, False, {"action_is_valid": True, "action_is_effective": False})
            logger.warning(f"Invalid arguments for tool: {error_msg} end-------")
            continue

        # Group by tool name
        if tool_name not in tool_groups:
            tool_groups[tool_name] = []
            tool_indices[tool_name] = []
            env_indices[tool_name] = []
            raw_prediction_indices[tool_name] = []

        tool_groups[tool_name].append(tool_args)
        tool_indices[tool_name].append(i)
        env_indices[tool_name].append(env)
        raw_prediction_indices[tool_name].append(action_text)

    # Second pass: execute tools in batch where possible
    for tool_name, args_list in tool_groups.items():
        indices = tool_indices[tool_name]
        envs_list = env_indices[tool_name]

        # All environments share the same tool instances, so we can use the first one
        tool = envs_list[0].tool_map[tool_name]
        raw_prediction_list = raw_prediction_indices[tool_name]
        try:
            # Try batch execution
            if isinstance(tool, WebBrowserTool):
                batch_results = tool.batch_execute(args_list, envs_list, raw_prediction_list)
            else:
                batch_results = tool.batch_execute(args_list)
            
            logger.debug(f"Batch execution results for tool '{tool_name}': {batch_results}")

            # --- 第 1 步：并发提交 `calculate_reward` 任务 ---
            future_to_idx = {}
            for idx_i, (env, result, args) in enumerate(zip(envs_list, batch_results, args_list)):
                # 提交 calculate_reward 函数作为任务
                future = env.owner_actor.submit(
                    tool.calculate_reward, 
                    args, 
                    result, 
                    env, 
                    env.PENALTY_FOR_INEFFECTIVE
                )
                future_to_idx[future] = idx_i

            # --- 第 2 步：异步收集所有计算好的 reward ---
            # 使用一个字典来存储 idx -> reward 的映射，确保顺序正确
            
            calculated_rewards = [None] * len(envs_list)
            for future in concurrent.futures.as_completed(future_to_idx):
                idx_i = future_to_idx[future]
                env = envs_list[idx_i] # 获取对应的env，主要用于异常处理时的penalty
                
                try:
                    # 获取计算结果
                    reward = future.result()
                    calculated_rewards[idx_i] = reward
                except Exception as exc:
                    # 如果 calculate_reward 内部发生异常，记录日志并使用惩罚值
                    logger.error(f"ERROR: Reward calculation for batch item index {idx_i} failed: {exc}. Using penalty.")
                    calculated_rewards[idx_i] = env.PENALTY_FOR_INEFFECTIVE

            # --- 第 3 步：使用预先计算好的 reward，完成剩余的串行处理 ---
            # 原始循环，但现在不再调用 calculate_reward
            for idx, reward, env, result, args in zip(indices, calculated_rewards, envs_list, batch_results, args_list):
                env.steps_taken += 1

                # 记录工具调用历史
                env.tool_history.append({
                    "tool": tool_name,
                    "args": args,
                    "result": result
                })

                # 检查是否达到最大回合数
                done = env.steps_taken >= env.max_turns

                # 更新追踪变量
                action_text = action_texts[idx]
                action = action_map[idx][1]
                env._update_tracking_variables(
                    response=action_text,
                    action=action,
                    action_is_valid=True,
                    action_is_effective=True,
                    reward=reward
                )

                # 返回完整的结果字典作为观察值
                if not isinstance(result, dict):
                    result = {"content": str(result), "image": None}
                # 将最终结果存入正确的位置
                results[idx] = (result, reward, done, {"action_is_valid": True, "action_is_effective": True})
        
        except Exception as e:
            logger.error(f"Error during batch execution of tool '{tool_name}': {e}", exc_info=True)
            # Handle batch execution failure for all related environments
            for idx in indices:
                env = envs[idx]
                action_text = action_texts[idx]
                action = action_map[idx][1]
                result = {"content": f"Batch execution error for tool '{tool_name}': {str(e)}", "image": None}
                reward = env.PENALTY_FOR_INEFFECTIVE
                
                env.steps_taken += 1
                env._update_tracking_variables(
                    response=action_text,
                    action=action,
                    action_is_valid=True,
                    action_is_effective=False,
                    reward=reward
                )
                results[idx] = (result, reward, False, {"action_is_valid": True, "action_is_effective": False})
    
    return results

class ToolEnv:
    """
    Generic tool environment class, handling tool calls, history tracking, and state
    """
    INVALID_ACTION = {"tool": "invalid", "args": {}}
    PENALTY_FOR_INVALID = -0.05
    PENALTY_FOR_INEFFECTIVE = -0.01
    
    def __init__(self, tools: List[WebBrowserTool] = None, max_turns: int = 10):
        self.tools = tools or []
        self.tool_map = {tool.name: tool for tool in self.tools}
        self.tool_desc = [tool.get_description() for tool in self.tools]
        self.max_turns = max_turns
        self.reset_tracking_variables()

    def tools_format_func(self) -> str:
        template = """# Tools

Based on the web screen shot and content, you need call a function to help you fulfill the user's query.

You are provided with function signatures within <tools></tools> XML tags:
<tools>
{tools}
</tools>

For each function call, return a json object with function name and arguments within <tool_call></tool_call> XML tags:
<tool_call>
{{"name": <function-name>, "arguments": <args-json-object>}}
</tool_call>"""
        tools = "\n".join([f"{json.dumps(tool.get_description(), ensure_ascii=False)}" for tool in self.tools])
        return template.format(tools=tools)
        
    def reset_tracking_variables(self):
        self.rewards = []
        self.tool_history = []
        self.steps_taken = 0
        self._actions = []
        self._actions_valid = []
        self._actions_effective = []
    
    def get_tracking_variables(self) -> Dict:
        return {
            "rewards": self.rewards,
            "total_reward": sum(self.rewards),
            "steps_taken": self.steps_taken,
            "tool_history": self.tool_history,
            "actions": self._actions,
            "actions_valid": self._actions_valid,
            "actions_effective": self._actions_effective,
        }
    
    def _update_tracking_variables(
            self, 
            response: str,
            action: Any, 
            action_is_valid: bool,
            action_is_effective: bool,
            reward: float,
        ):
        self._actions.append(response)
        if action_is_valid:
            self._actions_valid.append(action)
        else:
            self._actions_valid.append(None)
        if action_is_effective:
            self._actions_effective.append(action)
        else:
            self._actions_effective.append(None)
        
        self.rewards.append(reward)
    
    def adjust_action_string(self,
        gpt_response_string: str, 
        grid_thw: list, 
        image_token_num: int, 
        image_file_list: list
    ) -> str:
        pattern = r'<tool_call>(.*?)</tool_call>'

        def replacer(match):
            json_content = match.group(1)

            try:
                action_data = json.loads(json_content)
            except json.JSONDecodeError:
                return match.group(0)

            if "arguments" not in action_data:
                return match.group(0)

            args = action_data["arguments"]
            action_name = action_data.get("name")
            
            coord_keys = ["coords", "from_coord", "to_coord"]
            needs_scaling = (
                any(key in args for key in coord_keys) or
                (action_name in ["scroll", "hscroll"] and "distance" in args)
            )

            if not needs_scaling:
                return match.group(0)

            idx = image_token_num - 1
            try:
                original_w, original_h = imagesize.get(image_file_list[idx])
            except (FileNotFoundError, IndexError, TypeError):
                return match.group(0)

            if original_w == 0 or original_h == 0:
                return match.group(0)

            resize_h = grid_thw[idx][1] * 14
            resize_w = grid_thw[idx][2] * 14

            def scale_coords(coords_list):
                if not isinstance(coords_list, list) or len(coords_list) != 2:
                    return coords_list
                rel_x, rel_y = coords_list
                abs_x = int(rel_x / original_w * resize_w)
                abs_y = int(rel_y / original_h * resize_h)
                return [abs_x, abs_y]

            for key in coord_keys:
                if key in args:
                    args[key] = scale_coords(args[key])

            if "distance" in args:
                rel_distance = args["distance"]
                if action_name == "scroll":
                    args["distance"] = int(rel_distance / original_h * resize_h)
                elif action_name == "hscroll":
                    args["distance"] = int(rel_distance / original_w * resize_w)
            
            updated_json_content = json.dumps(action_data, separators=(',', ':'))
            return f"<tool_call>{updated_json_content}</tool_call>"

        return re.sub(pattern, replacer, gpt_response_string, flags=re.DOTALL)

    def extract_answer(self, text: str):
        answer_pattern = r'<answer>(.*?)</answer>'
        answer_match = re.search(answer_pattern, text, re.DOTALL)
        if answer_match:
            return True
        else:
            return False
        

    def extract_tool_call(self, text: str) -> Dict:
        tool_call_pattern = r'<tool_call>(.*?)</tool_call>'
        tool_call_match = re.search(tool_call_pattern, text, re.DOTALL)
        
        if not tool_call_match:
            return self.INVALID_ACTION
        tool_call_json = ""
        try:
            tool_call_json = tool_call_match.group(1).strip()
            logger.debug(f"Extracted tool call JSON: {tool_call_json}")
            tool_call_data = json_repair.loads(tool_call_json)
            
            if "name" not in tool_call_data:
                return self.INVALID_ACTION
                
            tool_name = tool_call_data["name"]
            tool_args = tool_call_data.get("arguments", {})
            
            return {"tool": tool_name, "args": tool_args}
        except json.JSONDecodeError:
            logger.warning(f"Action JSONDecodeError for content: {tool_call_json}")
            return self.INVALID_ACTION
        except Exception:
            logger.error("An unexpected error occurred during action extraction.", exc_info=True)
            return self.INVALID_ACTION
    
    def get_tool_history_context(self) -> str:
        if not self.tool_history:
            return "No tool call history yet."
        
        context = "Tool call history:\n"
        for i, call in enumerate(self.tool_history):
            context += f"{i+1}. Tool: {call['tool']}\n"
            context += f"   Arguments: {json.dumps(call['args'], ensure_ascii=False)}\n"
            result = call['result']
            if isinstance(result, dict):
                content = result.get('content', '')
                # Truncate long content for brevity in history
                if len(content) > 200:
                    content = content[:200] + "..."
                context += f"   Result: {content}\n"
            else:
                str_result = str(result)
                if len(str_result) > 200:
                    str_result = str_result[:200] + "..."
                context += f"   Result: {str_result}\n"
            context += "\n"
        
        return context
    
    def get_available_tools_description(self) -> str:
        if not self.tools:
            return "No tools available."
            
        descriptions = ["Available tools:"]
        for tool in self.tools:
            descriptions.append(tool.get_simple_description())
            
        return "\n\n".join(descriptions)
    
    def copy(self):
        env = ToolEnv(tools=self.tools, max_turns=self.max_turns)
        env.tool_history = deepcopy(self.tool_history)
        env.rewards = deepcopy(self.rewards)
        env.steps_taken = self.steps_taken
        env._actions = deepcopy(self._actions)
        env._actions_valid = deepcopy(self._actions_valid)
        env._actions_effective = deepcopy(self._actions_effective)
        return env

def get_integer_after_prefix(text: str, prefix: str) -> int | None:
    """
    使用正则表达式从字符串中提取指定前缀后的整数。

    :param text: 原始字符串。
    :param prefix: 要查找的前缀。
    :return: 提取到的整数，如果未找到则返回 None。
    """
    # re.escape(prefix) 可以防止前缀中的特殊字符影响正则表达式
    pattern = re.compile(re.escape(prefix) + r"(\d+)")
    match = pattern.search(text)
    
    if match:
        return int(match.group(1))
    
    return None


class WebBrowserEnv(AsyncScriptBrowserEnv, ToolEnv):
    """
    Web Browser Environment combining async browser capabilities with a tool-based interface.
    """
    INVALID_ACTION = {"tool": "invalid", "args": {}}
    PENALTY_FOR_INVALID = -5 * 10**(-3)
    PENALTY_FOR_INEFFECTIVE = -1 *10**(-3)
    
    if "wPRALL" in EXPERIMENT_NAME:
        penalty_factor = get_integer_after_prefix(EXPERIMENT_NAME, "wPRALL")
        if penalty_factor is not None:
            PENALTY_FOR_INVALID = -5 * 10**(-penalty_factor)
            PENALTY_FOR_INEFFECTIVE = -1 *10**(-penalty_factor)
    logger.info(f"PENALTY_FOR_INVALID: {PENALTY_FOR_INVALID}, PENALTY_FOR_INEFFECTIVE: {PENALTY_FOR_INEFFECTIVE}")


    def __init__(self, with_wplaywright = True, max_turns: int = 30, **kwargs):

        if OBSERVATION_TYPE == "image_som":
            action_list = ACTION_ID_LIST
        else:
            action_list = ACTION_CORR_LIST

        tools = [WebBrowserTool(name=a['name'], description=a['description'], parameters=a['parameters']) for a in action_list]
        
        # Initialize ToolEnv parts
        self.tools = tools
        self.tool_map = {tool.name: tool for tool in self.tools}
        self.tool_desc = [tool.get_description() for tool in self.tools]
        self.max_turns = max_turns
        self.current_step = 1 #inital step in the dataloader
        self.reset_tracking_variables()
        
        # Initialize AsyncScriptBrowserEnv
        if with_wplaywright:
            AsyncScriptBrowserEnv.__init__(self, **kwargs)
            logger.info("AsyncScriptBrowserEnv initialized successfully.")

        self.owner_actor: Optional[BrowserActor] = None 


    def tools_format_func(self) -> str:
        template = """You are a helpful assistant.

# Tools

You may call one or more functions to assist with the user query.

You are provided with function signatures within <tools></tools> XML tags:
<tools>
{tools}
</tools>

For each function call, return a json object with function name and arguments within <tool_call></tool_call> XML tags:
<tool_call>
{{"name": <function-name>, "arguments": <args-json-object>}}
</tool_call>"""
        tools = "\n".join([f"{json.dumps(tool.get_description(), ensure_ascii=False)}" for tool in self.tools])
        return template.format(tools=tools)



async def a_create_clone_worker(config_file, storage_state, config, browser_unit, owner_actor):
    """异步地创建环境克隆。"""
    clone_context_id = f"{str(uuid.uuid4())}_clone_{str(uuid.uuid4())}"
    logger.debug(f"Creating new env clone. Context ID: {clone_context_id}")
    
    new_env = None
    
    try:
        with open(config_file, 'r', encoding='utf-8') as config_file_tmp:
            config_dict = json_repair.load(config_file_tmp)

            viewport_size = {
                "width": config.tool.webbrowser.viewport_width,
                "height": config.tool.webbrowser.viewport_height,
            }
        new_env = WebBrowserEnv(
            context_id = clone_context_id,
            headless = not config.tool.webbrowser.render,
            slow_mo = config.tool.webbrowser.slow_mo,
            observation_type = config.tool.webbrowser.observation_type,
            current_viewport_only = config.tool.webbrowser.current_viewport_only,
            viewport_size=viewport_size,
            save_trace_enabled = config.tool.webbrowser.save_trace_enabled,
            sleep_after_execution = config.tool.webbrowser.sleep_after_execution,
            # NOTE: captioning_fn here is used for LLM + captioning baselines.
            # This can be different from the captioning model used for evals.
            captioning_fn = config.tool.webbrowser.caption_image_fn,
            user_query=config_dict['intent']
        )
        new_env.owner_actor = owner_actor
        # areset 现在可以直接 await
        observation, _ = await new_env.areset(
            options={"config_file": config_file, "storage_state": storage_state},
            browser_unit=browser_unit
        )
        # 不再返回 loop，因为它由 Actor 管理
        return new_env, observation

    except Exception as exc:
        logger.error(f'Failed to create clone in a_create_clone_worker: {exc}', exc_info=True)
        if new_env and new_env.context:
            try:
                # 尝试异步关闭
                await new_env.aclose()
            except Exception as close_exc:
                logger.error(f"Error closing failed env during exception handling: {close_exc}")
        return None, None



global_ind = 0

async def init_env(script_env) -> None:
    observation, _ = await script_env.areset(options={'config_file': os.environ.get("TEST_CONFIG_FILE", './config_files/test.json')})

async def step_env(script_env) -> None:
    action = create_id_based_action("click [4]")
    observation, reward, terminated, truncated, info = await script_env.astep(action)

async def save_screen_image(script_env, env_name=""):
    """保存截图到指定路径"""
    obs_before_step, _ = await script_env._async_get_obs()
    logger.info(f"Observation shape: {obs_before_step.shape}")
    image = Image.fromarray(obs_before_step)
    
    # 如果 env_name 包含完整路径（带/），直接使用
    if '/' in env_name:
        image_path = f'{env_name}.png'
    else:
        # 否则使用默认路径
        global global_ind
        image_path = os.path.join(os.environ.get("SCREENSHOT_SAVE_DIR", "/tmp"), f'observation_{env_name}_{global_ind}.png')
        global_ind += 1
    
    # 确保目录存在
    import os
    os.makedirs(os.path.dirname(image_path), exist_ok=True)
    
    image.save(image_path)
    print(f"Saved observation image to {image_path}")
    return image_path

filename_list = ["1025.json"]#["1784.json"] #["1025.json"] * 1 #60
CONFIG_BASE_PATH = os.environ.get("CONFIG_BASE_PATH", "./config_files/")

# worker_task 的新签名
def worker_task(config_filename: str, browser_actor: BrowserActor) -> dict:
    # 不再需要在这里创建 actor 和 executor
    # browser_actor = BrowserActor(endpoint=ws_endpoint_list[0])
    # with concurrent.futures.ThreadPoolExecutor(max_workers=1) as executor:
    #     executor.submit(browser_actor.start())
    
    env = None
    start_time = time.time()
    result = {"config_file": config_filename, "status": "FAIL", "error": None, "actor_endpoint": browser_actor._endpoint}

    try:
        env = AsyncScriptBrowserEnv(context_id=f'test_{os.path.basename(config_filename)}', observation_type='image', viewport_size={"width": 1280, "height": 720})
        full_config_path = os.path.join(CONFIG_BASE_PATH, config_filename)
        
        options = {}
        #options={'config_file': full_config_path}
        #options = {'start_url': 'https://www.bilibili.com/'}
        #options={'start_url': 'https://search.bilibili.com/all?keyword=spss%E5%85%A5%E9%97%A8&from_source=webtop_search&spm_id_from=333.1007&search_source=5'}
        #options={'start_url': 'https://www.jd.com/'}
        #options={'start_url': 'https://www.weather.com.cn/'}
        #options={'start_url': 'https://env-00jxgx2bystb-static.normal.cloudstatic.cn/BHFHDCFFIDaD4dmf6zJx#/'}
        #options = {'start_url': 'https://news.sina.com.cn/'}
        #options = {'start_url': 'https://bilibili.com/'}
        #options = {'start_url': 'https://66law.cn/'}
        options['start_url'] = 'https://www.12306.cn/'
        #storage_state = get_storage_state_from_start_url(options['start_url'])
        #get_storage_state_from_start_url(options['start_url'])
        # storage_state = {
        #     "cookies": [],
        #     "origins": []
        # }
        #options['storage_state'] = storage_state
        #options['config_file'] = os.environ.get("TEST_CONFIG_FILE", "./config_files/test.json")
        # 使用传入的 actor 提交任务
        # browser_actor.submit(...) 返回一个 future，你需要获取它的结果
        # 使用 as_completed 来等待 future 完成
        f = browser_actor.submit(env.areset, options=options, browser_unit=browser_actor.browser_unit)
        print(options)
        concurrent.futures.wait([f]) # 等待 areset 完成
        f.result() # 检查 areset 是否有异常
        print("url: " + env.page.url)
        #action = create_coords_based_action("type [676, 29] [临汾] [1]")
        #action = create_coords_based_action("type [287, 247] [临汾] [1]")
        #action = create_coords_based_action("click [223, 241]")
        #action = create_coords_based_action("scroll [down] [500]")
        #action = create_coords_based_action("type [538, 93] [自营好侍百梦多原味咖喱] [1]")
        #action = create_coords_based_action("click [65, 113]")
        #action = create_coords_based_action("new_tab")
        #action = create_id_based_action("scroll [down]")
        # action = create_id_based_action("scroll [down]")
        # action = create_id_based_action("scroll [down]")
        #action = create_id_based_action("click [1]")
        #action = create_coords_based_action("type [944, 22] [临汾] [1]")
        action = create_coords_based_action("type [378, 278] [mianyang] [0]")
        f_step = browser_actor.submit(env.astep, action)
        concurrent.futures.wait([f_step])
        f_step.result()

        f_save = browser_actor.submit(save_screen_image, env, env_name='test') # 需要一个异步版本的 save_screen_image
        concurrent.futures.wait([f_save])
        f_save.result()
        #f_score = browser_actor.submit(env.get_score, "")
        print("config_file" + str(env.config_file))
        # concurrent.futures.wait([f_score])
        # result['score'] = f_score.result()
        # result["status"] = "SUCCESS"
    except Exception as e:
        logger.error(f"Task failed for config: {config_filename}", exc_info=True)
        result["error"] = str(e)
    finally:
        logger.info(f"Task finished, cleaning up resources for: {config_filename}")
        try:
            if env is not None:
                browser_actor.submit(env.aclose())
        except Exception as cleanup_exc:
            logger.error(f"Error during env cleanup: {cleanup_exc}")
    
    
    end_time = time.time()
    result["duration"] = round(end_time - start_time, 2)
    return result


# ==================== 新增和修改动作的测试用例 ====================

def start_http_server(directory: str, port: int = 8899):
    """
    启动一个简单的 HTTP 服务器来提供测试页面
    
    Args:
        directory: 要服务的目录路径
        port: 端口号
    
    Returns:
        (server, thread) 服务器对象和线程
    """
    class Handler(SimpleHTTPRequestHandler):
        def __init__(self, *args, **kwargs):
            super().__init__(*args, directory=directory, **kwargs)
        
        def log_message(self, format, *args):
            # 静默日志输出
            pass
    
    # 使用 TCPServer with allow_reuse_address
    socketserver.TCPServer.allow_reuse_address = True
    server = socketserver.TCPServer(("", port), Handler)
    
    # 在后台线程中运行服务器
    thread = threading.Thread(target=server.serve_forever, daemon=True)
    thread.start()
    
    print(f"✓ HTTP 服务器已启动在端口 {port}")
    print(f"  服务目录: {directory}")
    
    return server, thread


def test_actions_with_browser(browser_actor: BrowserActor, test_output_dir: str):
    """
    在真实浏览器中测试新增和修改的动作
    
    Args:
        browser_actor: 浏览器 Actor 实例
        test_output_dir: 测试截图保存目录
    """
    import os
    os.makedirs(test_output_dir, exist_ok=True)
    
    env = None
    test_results = []
    http_server = None
    
    try:
        # 启动 HTTP 服务器
        test_pages_dir = Path(__file__).parent / "test_pages"
        http_port = 8899
        
        print("\n" + "="*80)
        print("准备测试环境")
        print("="*80)
        
        try:
            http_server, server_thread = start_http_server(str(test_pages_dir), http_port)
            time.sleep(2)  # 等待服务器启动
        except Exception as e:
            logger.warning(f"启动 HTTP 服务器失败: {e}，将使用 file:// 协议")
            http_server = None
        
        # 创建浏览器环境
        env = AsyncScriptBrowserEnv(
            context_id='action_test',
            observation_type='image',
            viewport_size={"width": 1280, "height": 720}
        )
        
        print("\n" + "="*80)
        print("开始浏览器动作测试")
        print("="*80 + "\n")
        
        # ==================== 测试 1: Scroll 动作（四个方向） ====================
        print("📋 测试 1: Scroll 动作测试")
        print("-"*80)
        
        # 使用 HTTP 或 file:// 协议
        if http_server:
            scroll_page = f"http://localhost:{http_port}/test_scroll.html"
        else:
            scroll_page = f"file://{test_pages_dir}/test_scroll.html"
        
        print(f"准备加载: {scroll_page}")
        options = {'start_url': scroll_page}
        
        # 添加重试逻辑
        max_load_retries = 3
        for load_attempt in range(max_load_retries):
            try:
                f = browser_actor.submit(env.areset, options=options, browser_unit=browser_actor.browser_unit)
                concurrent.futures.wait([f], timeout=120)  # 增加超时时间
                f.result()
                print(f"✓ 加载测试页面成功 (尝试 {load_attempt + 1}/{max_load_retries})")
                break
            except Exception as e:
                logger.warning(f"加载页面失败 (尝试 {load_attempt + 1}/{max_load_retries}): {e}")
                if load_attempt < max_load_retries - 1:
                    print(f"  等待 5 秒后重试...")
                    time.sleep(5)
                else:
                    raise Exception(f"无法加载测试页面，已重试 {max_load_retries} 次: {e}")
        
        # 保存初始状态
        f_save = browser_actor.submit(save_screen_image, env, env_name=f'{test_output_dir}/01_scroll_initial')
        concurrent.futures.wait([f_save])
        f_save.result()
        print(f"  截图: 01_scroll_initial.png")
        
        # 测试向下滚动
        action = create_coords_based_action("scroll [down] [500]")
        f_step = browser_actor.submit(env.astep, action)
        concurrent.futures.wait([f_step])
        f_step.result()
        
        f_save = browser_actor.submit(save_screen_image, env, env_name=f'{test_output_dir}/02_scroll_down')
        concurrent.futures.wait([f_save])
        f_save.result()
        print(f"  ✓ scroll [down] [500] - 截图: 02_scroll_down.png")
        
        # 测试向右滚动
        action = create_coords_based_action("scroll [right] [600]")
        f_step = browser_actor.submit(env.astep, action)
        concurrent.futures.wait([f_step])
        f_step.result()
        
        f_save = browser_actor.submit(save_screen_image, env, env_name=f'{test_output_dir}/03_scroll_right')
        concurrent.futures.wait([f_save])
        f_save.result()
        print(f"  ✓ scroll [right] [600] - 截图: 03_scroll_right.png")
        
        # 测试向上滚动
        action = create_coords_based_action("scroll [up] [300]")
        f_step = browser_actor.submit(env.astep, action)
        concurrent.futures.wait([f_step])
        f_step.result()
        
        f_save = browser_actor.submit(save_screen_image, env, env_name=f'{test_output_dir}/04_scroll_up')
        concurrent.futures.wait([f_save])
        f_save.result()
        print(f"  ✓ scroll [up] [300] - 截图: 04_scroll_up.png")
        
        # 测试向左滚动
        action = create_coords_based_action("scroll [left] [400]")
        f_step = browser_actor.submit(env.astep, action)
        concurrent.futures.wait([f_step])
        f_step.result()
        
        f_save = browser_actor.submit(save_screen_image, env, env_name=f'{test_output_dir}/05_scroll_left')
        concurrent.futures.wait([f_save])
        f_save.result()
        print(f"  ✓ scroll [left] [400] - 截图: 05_scroll_left.png")
        
        # 测试在特定位置滚动
        action = create_coords_based_action("scroll [down] [500] [300, 400]")
        f_step = browser_actor.submit(env.astep, action)
        concurrent.futures.wait([f_step])
        f_step.result()
        
        f_save = browser_actor.submit(save_screen_image, env, env_name=f'{test_output_dir}/06_scroll_at_coords')
        concurrent.futures.wait([f_save])
        f_save.result()
        print(f"  ✓ scroll [down] [500] [300, 400] - 截图: 06_scroll_at_coords.png")
        
        test_results.append({"test": "Scroll 四个方向", "status": "PASS"})
        print("\n✅ Scroll 测试完成\n")
        
        # ==================== 测试 2: Find 动作 ====================
        print("📋 测试 2: Find 动作测试")
        print("-"*80)
        
        # 使用 HTTP 或 file:// 协议
        if http_server:
            find_page = f"http://localhost:{http_port}/test_find.html"
        else:
            find_page = f"file://{test_pages_dir}/test_find.html"
        
        options = {'start_url': find_page}
        
        for load_attempt in range(max_load_retries):
            try:
                f = browser_actor.submit(env.areset, options=options, browser_unit=browser_actor.browser_unit)
                concurrent.futures.wait([f], timeout=120)
                f.result()
                print(f"✓ 加载测试页面成功 (尝试 {load_attempt + 1}/{max_load_retries})")
                break
            except Exception as e:
                logger.warning(f"加载页面失败 (尝试 {load_attempt + 1}/{max_load_retries}): {e}")
                if load_attempt < max_load_retries - 1:
                    print(f"  等待 5 秒后重试...")
                    time.sleep(5)
                else:
                    raise Exception(f"无法加载测试页面: {e}")
        
        # 保存初始状态
        f_save = browser_actor.submit(save_screen_image, env, env_name=f'{test_output_dir}/07_find_initial')
        concurrent.futures.wait([f_save])
        f_save.result()
        print(f"  截图: 07_find_initial.png")
        
        # 搜索"目标文本"
        action = create_coords_based_action("find [目标文本]")
        f_step = browser_actor.submit(env.astep, action)
        concurrent.futures.wait([f_step])
        f_step.result()
        
        f_save = browser_actor.submit(save_screen_image, env, env_name=f'{test_output_dir}/08_find_target')
        concurrent.futures.wait([f_save])
        f_save.result()
        print(f"  ✓ find [目标文本] - 截图: 08_find_target.png")
        
        # 搜索"登录"
        action = create_coords_based_action("find [登录]")
        f_step = browser_actor.submit(env.astep, action)
        concurrent.futures.wait([f_step])
        f_step.result()
        
        f_save = browser_actor.submit(save_screen_image, env, env_name=f'{test_output_dir}/09_find_login')
        concurrent.futures.wait([f_save])
        f_save.result()
        print(f"  ✓ find [登录] - 截图: 09_find_login.png")
        
        # 搜索隐藏内容"确定"
        action = create_coords_based_action("find [确定]")
        f_step = browser_actor.submit(env.astep, action)
        concurrent.futures.wait([f_step])
        f_step.result()
        
        f_save = browser_actor.submit(save_screen_image, env, env_name=f'{test_output_dir}/10_find_hidden')
        concurrent.futures.wait([f_save])
        f_save.result()
        print(f"  ✓ find [确定] (隐藏内容) - 截图: 10_find_hidden.png")
        
        test_results.append({"test": "Find 文本搜索", "status": "PASS"})
        print("\n✅ Find 测试完成\n")
        
        # ==================== 测试 3: Get_File 动作 ====================
        print("📋 测试 3: Get_File 动作测试")
        print("-"*80)
        
        # 使用 HTTP 或 file:// 协议
        if http_server:
            getfile_page = f"http://localhost:{http_port}/test_get_file.html"
        else:
            getfile_page = f"file://{test_pages_dir}/test_get_file.html"
        
        options = {'start_url': getfile_page}
        
        for load_attempt in range(max_load_retries):
            try:
                f = browser_actor.submit(env.areset, options=options, browser_unit=browser_actor.browser_unit)
                concurrent.futures.wait([f], timeout=120)
                f.result()
                print(f"✓ 加载测试页面成功 (尝试 {load_attempt + 1}/{max_load_retries})")
                break
            except Exception as e:
                logger.warning(f"加载页面失败 (尝试 {load_attempt + 1}/{max_load_retries}): {e}")
                if load_attempt < max_load_retries - 1:
                    print(f"  等待 5 秒后重试...")
                    time.sleep(5)
                else:
                    raise Exception(f"无法加载测试页面: {e}")
        
        # 保存初始状态
        f_save = browser_actor.submit(save_screen_image, env, env_name=f'{test_output_dir}/11_getfile_initial')
        concurrent.futures.wait([f_save])
        f_save.result()
        print(f"  截图: 11_getfile_initial.png")
        
        # 测试获取 PDF 文件 (坐标约 200, 400)
        action = create_coords_based_action("get_file [230, 470]")
        f_step = browser_actor.submit(env.astep, action)
        concurrent.futures.wait([f_step])
        f_step.result()
        
        f_save = browser_actor.submit(save_screen_image, env, env_name=f'{test_output_dir}/12_getfile_pdf')
        concurrent.futures.wait([f_save])
        f_save.result()
        print(f"  ✓ get_file [230, 470] (PDF) - 截图: 12_getfile_pdf.png")
        
        # 滚动到图片区域
        action = create_coords_based_action("scroll [down] [800]")
        f_step = browser_actor.submit(env.astep, action)
        concurrent.futures.wait([f_step])
        f_step.result()
        
        # 测试获取图片 (坐标约 120, 1100，滚动后变为可见区域)
        action = create_coords_based_action("get_file [150, 400]")
        f_step = browser_actor.submit(env.astep, action)
        concurrent.futures.wait([f_step])
        f_step.result()
        
        f_save = browser_actor.submit(save_screen_image, env, env_name=f'{test_output_dir}/13_getfile_image')
        concurrent.futures.wait([f_save])
        f_save.result()
        print(f"  ✓ get_file [150, 400] (Image) - 截图: 13_getfile_image.png")
        
        test_results.append({"test": "Get_File 文件获取", "status": "PASS"})
        print("\n✅ Get_File 测试完成\n")
        
        # ==================== 测试总结 ====================
        print("="*80)
        print("测试总结")
        print("="*80)
        for result in test_results:
            status_icon = "✅" if result["status"] == "PASS" else "❌"
            print(f"{status_icon} {result['test']}: {result['status']}")
        
        print(f"\n📁 所有截图已保存到: {test_output_dir}")
        print("="*80 + "\n")
        
    except Exception as e:
        logger.error(f"浏览器测试失败: {e}", exc_info=True)
        test_results.append({"test": "整体测试", "status": "FAIL", "error": str(e)})
    finally:
        # 清理环境
        if env is not None:
            try:
                browser_actor.submit(env.aclose())
            except Exception as cleanup_exc:
                logger.error(f"环境清理失败: {cleanup_exc}")
        
        # 关闭 HTTP 服务器
        if http_server is not None:
            try:
                http_server.shutdown()
                print("✓ HTTP 服务器已关闭")
            except Exception as e:
                logger.warning(f"关闭 HTTP 服务器失败: {e}")
    
    return test_results


def test_new_actions():
    """测试新增和修改的动作"""
    print("\n" + "="*60)
    print("测试新增和修改的动作")
    print("="*60 + "\n")
    
    # 测试 1: find 动作
    print("测试 1: find 动作")
    print("-" * 40)
    find_action_str = "find [登录]"
    find_action = create_coords_based_action(find_action_str)
    print(f"输入: {find_action_str}")
    print(f"解析结果: {find_action}")
    assert find_action is not None, "find 动作解析失败"
    assert find_action["action_type"] == 24, f"find 动作类型错误，期望 24，实际 {find_action['action_type']}"
    assert find_action["search_term"] == "登录", f"search_term 错误，期望 '登录'，实际 '{find_action['search_term']}'"
    print("✓ find 动作测试通过\n")
    
    # 测试 2: get_file 动作
    print("测试 2: get_file 动作")
    print("-" * 40)
    get_file_action_str = "get_file [500, 300]"
    get_file_action = create_coords_based_action(get_file_action_str)
    print(f"输入: {get_file_action_str}")
    print(f"解析结果: {get_file_action}")
    assert get_file_action is not None, "get_file 动作解析失败"
    assert get_file_action["action_type"] == 25, f"get_file 动作类型错误，期望 25，实际 {get_file_action['action_type']}"
    assert get_file_action["coords"][0] == 500, f"coords[0] 错误，期望 500，实际 {get_file_action['coords'][0]}"
    assert get_file_action["coords"][1] == 300, f"coords[1] 错误，期望 300，实际 {get_file_action['coords'][1]}"
    print("✓ get_file 动作测试通过\n")
    
    # 测试 3: scroll 垂直滚动（向上）
    print("测试 3: scroll 垂直滚动（向上）")
    print("-" * 40)
    scroll_up_str = "scroll [up] [500]"
    scroll_up_action = create_coords_based_action(scroll_up_str)
    print(f"输入: {scroll_up_str}")
    print(f"解析结果: {scroll_up_action}")
    assert scroll_up_action is not None, "scroll up 动作解析失败"
    assert scroll_up_action["action_type"] == 1, f"scroll 动作类型错误，期望 1，实际 {scroll_up_action['action_type']}"
    assert scroll_up_action["direction"] == "up", f"direction 错误，期望 'up'，实际 '{scroll_up_action['direction']}'"
    assert scroll_up_action["nth"] == 500, f"distance 错误，期望 500，实际 {scroll_up_action['nth']}"
    print("✓ scroll up 动作测试通过\n")
    
    # 测试 4: scroll 垂直滚动（向下）
    print("测试 4: scroll 垂直滚动（向下）")
    print("-" * 40)
    scroll_down_str = "scroll [down] [800]"
    scroll_down_action = create_coords_based_action(scroll_down_str)
    print(f"输入: {scroll_down_str}")
    print(f"解析结果: {scroll_down_action}")
    assert scroll_down_action is not None, "scroll down 动作解析失败"
    assert scroll_down_action["action_type"] == 1, f"scroll 动作类型错误，期望 1，实际 {scroll_down_action['action_type']}"
    assert scroll_down_action["direction"] == "down", f"direction 错误，期望 'down'，实际 '{scroll_down_action['direction']}'"
    assert scroll_down_action["nth"] == 800, f"distance 错误，期望 800，实际 {scroll_down_action['nth']}"
    print("✓ scroll down 动作测试通过\n")
    
    # 测试 5: scroll 水平滚动（向左）
    print("测试 5: scroll 水平滚动（向左）")
    print("-" * 40)
    scroll_left_str = "scroll [left] [300]"
    scroll_left_action = create_coords_based_action(scroll_left_str)
    print(f"输入: {scroll_left_str}")
    print(f"解析结果: {scroll_left_action}")
    assert scroll_left_action is not None, "scroll left 动作解析失败"
    assert scroll_left_action["action_type"] == 1, f"scroll 动作类型错误，期望 1，实际 {scroll_left_action['action_type']}"
    assert scroll_left_action["direction"] == "left", f"direction 错误，期望 'left'，实际 '{scroll_left_action['direction']}'"
    assert scroll_left_action["nth"] == 300, f"distance 错误，期望 300，实际 {scroll_left_action['nth']}"
    print("✓ scroll left 动作测试通过\n")
    
    # 测试 6: scroll 水平滚动（向右）
    print("测试 6: scroll 水平滚动（向右）")
    print("-" * 40)
    scroll_right_str = "scroll [right] [400]"
    scroll_right_action = create_coords_based_action(scroll_right_str)
    print(f"输入: {scroll_right_str}")
    print(f"解析结果: {scroll_right_action}")
    assert scroll_right_action is not None, "scroll right 动作解析失败"
    assert scroll_right_action["action_type"] == 1, f"scroll 动作类型错误，期望 1，实际 {scroll_right_action['action_type']}"
    assert scroll_right_action["direction"] == "right", f"direction 错误，期望 'right'，实际 '{scroll_right_action['direction']}'"
    assert scroll_right_action["nth"] == 400, f"distance 错误，期望 400，实际 {scroll_right_action['nth']}"
    print("✓ scroll right 动作测试通过\n")
    
    # 测试 7: scroll 带坐标的垂直滚动
    print("测试 7: scroll 带坐标的垂直滚动")
    print("-" * 40)
    scroll_coords_str = "scroll [down] [500] [600, 400]"
    scroll_coords_action = create_coords_based_action(scroll_coords_str)
    print(f"输入: {scroll_coords_str}")
    print(f"解析结果: {scroll_coords_action}")
    assert scroll_coords_action is not None, "scroll with coords 动作解析失败"
    assert scroll_coords_action["action_type"] == 1, f"scroll 动作类型错误，期望 1，实际 {scroll_coords_action['action_type']}"
    assert scroll_coords_action["direction"] == "down", f"direction 错误，期望 'down'，实际 '{scroll_coords_action['direction']}'"
    assert scroll_coords_action["nth"] == 500, f"distance 错误，期望 500，实际 {scroll_coords_action['nth']}"
    assert scroll_coords_action["coords"] is not None, "coords 不应为 None"
    assert scroll_coords_action["coords"][0] == 600, f"coords[0] 错误，期望 600，实际 {scroll_coords_action['coords'][0]}"
    assert scroll_coords_action["coords"][1] == 400, f"coords[1] 错误，期望 400，实际 {scroll_coords_action['coords'][1]}"
    print("✓ scroll with coords 动作测试通过\n")
    
    # 测试 8: scroll 带坐标的水平滚动
    print("测试 8: scroll 带坐标的水平滚动")
    print("-" * 40)
    scroll_h_coords_str = "scroll [right] [300] [800, 500]"
    scroll_h_coords_action = create_coords_based_action(scroll_h_coords_str)
    print(f"输入: {scroll_h_coords_str}")
    print(f"解析结果: {scroll_h_coords_action}")
    assert scroll_h_coords_action is not None, "horizontal scroll with coords 动作解析失败"
    assert scroll_h_coords_action["action_type"] == 1, f"scroll 动作类型错误，期望 1，实际 {scroll_h_coords_action['action_type']}"
    assert scroll_h_coords_action["direction"] == "right", f"direction 错误，期望 'right'，实际 '{scroll_h_coords_action['direction']}'"
    assert scroll_h_coords_action["nth"] == 300, f"distance 错误，期望 300，实际 {scroll_h_coords_action['nth']}"
    assert scroll_h_coords_action["coords"] is not None, "coords 不应为 None"
    assert scroll_h_coords_action["coords"][0] == 800, f"coords[0] 错误，期望 800，实际 {scroll_h_coords_action['coords'][0]}"
    assert scroll_h_coords_action["coords"][1] == 500, f"coords[1] 错误，期望 500，实际 {scroll_h_coords_action['coords'][1]}"
    print("✓ horizontal scroll with coords 动作测试通过\n")
    
    print("="*60)
    print("所有测试通过！✓")
    print("="*60 + "\n")


def test_web_browser_tool_conversion():
    """测试 WebBrowserTool 的 convert_action_to_string_coords 函数"""
    print("\n" + "="*60)
    print("测试 WebBrowserTool 的动作转换")
    print("="*60 + "\n")
    
    # 创建一个模拟的环境对象
    class MockEnv:
        def __init__(self):
            self.viewport_size = {'width': 1000, 'height': 1000}
    
    mock_env = MockEnv()
    
    # 测试 1: find 动作转换
    print("测试 1: find 动作转换")
    print("-" * 40)
    tool = WebBrowserTool(name="find")
    properties = {"search_term": "测试文本"}
    result = tool.convert_action_to_string_coords(properties, mock_env)
    print(f"输入: {properties}")
    print(f"输出: {result}")
    assert result == "find [测试文本]", f"转换错误，期望 'find [测试文本]'，实际 '{result}'"
    print("✓ find 动作转换测试通过\n")
    
    # 测试 2: get_file 动作转换（带坐标反缩放）
    print("测试 2: get_file 动作转换")
    print("-" * 40)
    tool = WebBrowserTool(name="get_file")
    properties = {"coords": [500, 600]}  # 在 1000x1000 的 resized 空间中
    result = tool.convert_action_to_string_coords(properties, mock_env)
    print(f"输入: {properties}")
    print(f"输出: {result}")
    # 坐标应该从 resized 空间转换回原始空间：(500/1000)*1000 = 500
    assert "get_file" in result, f"转换结果应包含 'get_file'"
    print("✓ get_file 动作转换测试通过\n")
    
    # 测试 3: scroll 动作转换（四个方向）
    print("测试 3: scroll 动作转换（四个方向）")
    print("-" * 40)
    tool = WebBrowserTool(name="scroll")
    for direction in ["up", "down", "left", "right"]:
        properties = {"direction": direction, "distance": 500}
        result = tool.convert_action_to_string_coords(properties, mock_env)
        print(f"输入: {properties}")
        print(f"输出: {result}")
        assert f"scroll [{direction}]" in result, f"转换结果应包含 'scroll [{direction}]'"
        assert "[500]" in result, f"转换结果应包含距离 [500]"
    print("✓ scroll 四个方向转换测试通过\n")
    
    # 测试 4: scroll 带坐标的动作转换
    print("测试 4: scroll 带坐标的动作转换")
    print("-" * 40)
    tool = WebBrowserTool(name="scroll")
    properties = {"direction": "down", "distance": 500, "coords": [600, 700]}
    result = tool.convert_action_to_string_coords(properties, mock_env)
    print(f"输入: {properties}")
    print(f"输出: {result}")
    assert "scroll [down]" in result, f"转换结果应包含 'scroll [down]'"
    assert "[500]" in result, f"转换结果应包含距离 [500]"
    # 应该包含转换后的坐标
    print("✓ scroll 带坐标转换测试通过\n")
    
    print("="*60)
    print("所有 WebBrowserTool 转换测试通过！✓")
    print("="*60 + "\n")


if __name__ == "__main__":
    import sys
    
    # 检查是否是测试模式
    if len(sys.argv) > 1 and sys.argv[1] == "test":
        print("\n运行单元测试模式...\n")
        try:
            test_new_actions()
            test_web_browser_tool_conversion()
            print("\n✓ 所有单元测试成功完成！\n")
        except AssertionError as e:
            print(f"\n✗ 测试失败: {e}\n")
            sys.exit(1)
        except Exception as e:
            print(f"\n✗ 测试过程中发生错误: {e}\n")
            import traceback
            traceback.print_exc()
            sys.exit(1)
        sys.exit(0)
    
    # 检查是否是浏览器测试模式
    if len(sys.argv) > 1 and sys.argv[1] == "browser_test":
        print("\n运行浏览器交互测试模式...\n")
        
        # 确保有浏览器端点
        if not ws_endpoint_list:
            print("❌ 错误: 没有可用的浏览器 WebSocket 端点")
            print(f"请检查配置目录: {BROWSER_OUTPUT_PATH}")
            sys.exit(1)
        
        print(f"找到 {len(ws_endpoint_list)} 个浏览器端点")
        
        # 初始化浏览器 Actor
        actor_pool = initialize_browser_actor_pool(
            ws_endpoint_list=ws_endpoint_list,
            webbrowser_thread_executor=concurrent.futures.ThreadPoolExecutor(max_workers=1)
        )
        
        if not actor_pool:
            print("❌ 错误: 无法初始化浏览器 Actor")
            sys.exit(1)
        
        browser_actor = actor_pool[0]
        print(f"✓ 浏览器 Actor 已初始化: {browser_actor._endpoint}\n")
        
        # 设置输出目录
        test_output_dir = Path(__file__).parent / "test_pages" / "screenshots"
        test_output_dir.mkdir(parents=True, exist_ok=True)
        
        try:
            # 运行浏览器测试
            results = test_actions_with_browser(browser_actor, str(test_output_dir))
            
            # 检查结果
            all_passed = all(r["status"] == "PASS" for r in results)
            if all_passed:
                print("\n✅ 所有浏览器测试通过！\n")
                sys.exit(0)
            else:
                print("\n❌ 部分测试失败\n")
                sys.exit(1)
                
        except Exception as e:
            print(f"\n❌ 浏览器测试失败: {e}\n")
            import traceback
            traceback.print_exc()
            sys.exit(1)
        finally:
            # 清理
            try:
                browser_actor.stop()
            except Exception as e:
                logger.error(f"停止 Actor 失败: {e}")
        
        sys.exit(0)
    
    # 正常运行模式
    # MAX_WORKERS = 1  # 这现在控制的是任务并发数，而不是浏览器并发数
    
    # # 1. 初始化 Actor Pool
    # actor_pool = initialize_browser_actor_pool(ws_endpoint_list=ws_endpoint_list,
    #     webbrowser_thread_executor=concurrent.futures.ThreadPoolExecutor(max_workers=len(ws_endpoint_list))
    # )
    # if not actor_pool:
    #     logger.critical("Failed to initialize any browser actors. Exiting.")
    #     exit(1)

    # logger.info(f"Starting parallel processing for {len(filename_list)} configs using a pool of {len(actor_pool)} actors.")

    # all_results = []
    
    # # 2. 使用 ThreadPoolExecutor 来分发任务
    # # MAX_WORKERS 应该 <= len(actor_pool) 以获得最佳性能
    # with concurrent.futures.ThreadPoolExecutor(max_workers=MAX_WORKERS) as executor:
    #     future_to_config = {}
        
    #     # 使用 itertools.cycle 来循环使用 actor 池
    #     import itertools
    #     actor_cycle = itertools.cycle(actor_pool)

    #     for filename in filename_list:
    #         # 从池中获取一个 actor
    #         actor_for_task = next(actor_cycle)
    #         # 提交任务，将 actor 传进去
    #         future = executor.submit(worker_task, filename, actor_for_task)
    #         future_to_config[future] = filename
        
    #     for future in concurrent.futures.as_completed(future_to_config):
    #         config_name = future_to_config[future]
    #         try:
    #             data = future.result()
    #             all_results.append(data)
    #             logger.info(f"Task completed: {data}")
    #         except Exception as exc:
    #             logger.critical(f"Config {config_name} generated a critical error: {exc}", exc_info=True)
    #             all_results.append({"config_file": config_name, "status": "CRASH", "error": str(exc)})

    # # 3. 关闭 Actor Pool
    # logger.info("All tasks completed. Shutting down browser actor pool...")
    # for actor in actor_pool:
    #     try:
    #         actor.stop()
    #     except Exception as e:
    #         logger.error(f"Error stopping actor {actor._endpoint}: {e}")


    
    # import json
    # from recipe.fully_async_policy.browser_env.utils import DetachedPage, png_bytes_to_numpy, Observation, StateInfo
    # from recipe.fully_async_policy.browser_env.actions import Action
    # import pprint
    # script_env = AsyncScriptBrowserEnv()
    # # await _test(script_env)
    # # asyncio.run(_test2(script_env))
    # loop = asyncio.new_event_loop()
    # asyncio.set_event_loop(loop)     # 绑定到当前线程
    # loop.run_until_complete(init_env(script_env))
    # save_screen_image(script_env, loop, env_name='init1')
    # loop.run_until_complete(step_env(script_env))
    # save_screen_image(script_env, loop, env_name='init1')
    # # loop.run_until_complete(step_env(script_env))
    # # save_screen_image(script_env, loop, env_name='init1')
    # score = loop.run_until_complete(script_env.get_score(""))
    # loop.run_until_complete(script_env.aclose())
    # loop.close()
    # print(score)